strictness: medium
test-warnings: false
doc-warnings: false
member-warnings: false

ignore-paths:
  - tests
  - compiled-mibs
  - compiled-mibs-test
  - retired
  - minimal_for_reference
  - manual-tests
  - logs
  - ui/logs
  - snmp_wrapper

tools:
  dodgy:
    run: true
  mccabe:
    run: true
  pycodestyle:
    run: false
  pyflakes:
    run: true
  pylint:
    run: true
