"""Schema generation from compiled MIB files."""
# pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-locals,too-many-nested-blocks,too-few-public-methods

import contextlib
import json
import os
import re
from collections.abc import Iterable
from pathlib import Path
from typing import Any, Protocol, cast

from pysnmp.smi import builder

from app.app_logger import AppLogger
from app.default_value_plugins import get_default_value
from app.interface_types import (
    HasDescription,
    HasGetIndexNames,
    HasIndexNames,
    HasNamedValues,
    HasObjects,
    HasStatus,
    HasSubtypeSpec,
    HasValues,
)
from app.json_format import dumps_with_horizontal_oid_lists
from app.mib_builder_adapters import extract_symbol_snapshot
from app.model_paths import AGENT_MODEL_DIR, TYPE_REGISTRY_FILE
from app.plugin_loader import load_plugins

logger = AppLogger.get(__name__)

SCHEMA_VERSION = "1.0.1"
MIB_OPERATION_ERRORS = (
    AttributeError,
    LookupError,
    OSError,
    TypeError,
    ValueError,
    RuntimeError,
    KeyError,
)


class SymbolSnapshot(Protocol):
    """Protocol for symbol snapshots extracted from MIB symbols."""

    @property
    def class_name(self) -> str:
        """Return the class name of the MIB symbol (e.g., 'MibTable', 'MibScalar')."""
        raise NotImplementedError

    @property
    def oid(self) -> tuple[int, ...]:
        """Return the OID tuple for this symbol."""
        raise NotImplementedError

    @property
    def syntax_obj(self) -> object | None:
        """Return the syntax object associated with this symbol, or None."""
        raise NotImplementedError

    @property
    def access(self) -> str:
        """Return the access level for this symbol (e.g., 'read-only', 'read-write')."""
        raise NotImplementedError


class BehaviourGenerator:
    """Generates schema.json files from compiled MIB Python files.

    Implements the three-file architecture:
    - schema.json: Structure + initial values (generated by this class)
    - behaviour.json: Dynamic functions (optional, user-created)
    - values.json: Runtime state (created by agent at runtime)

    Output structure: {output_dir}/{MIB_NAME}/schema.json
    """

    def __init__(
        self,
        output_dir: str = str(AGENT_MODEL_DIR),
        *,
        load_default_plugins: bool = True,
    ) -> None:
        """Initialize the generator and load optional default plugins."""
        self.output_dir = output_dir
        self._type_registry: dict[str, Any] = {}
        Path(self.output_dir).mkdir(parents=True, exist_ok=True)

        # Load plugins on initialization
        if load_default_plugins:
            loaded = load_plugins()
            logger.info(
                "Loaded %d default value plugins: %s",
                len(loaded),
                ", ".join(loaded),
            )

    def generate(
        self,
        compiled_py_path: str,
        mib_name: str | None = None,
        *,
        force_regenerate: bool = True,
    ) -> str:
        """Generate schema JSON from a compiled MIB Python file.

        Creates a directory structure: {output_dir}/{MIB_NAME}/schema.json
        This follows the three-file architecture:
        - schema.json (generated, structure + initial values)
        - behaviour.json (optional, user-created, dynamic functions)
        - values.json (runtime, agent-created, current state)

        Args:
            compiled_py_path: Path to the compiled MIB .py file
            mib_name: Name of the MIB module (optional, will be parsed if not provided)
            force_regenerate: If False, skip if schema.json already exists

        Returns:
            Path to the generated schema.json file

        """
        if mib_name is None:
            mib_name = self._parse_mib_name_from_py(compiled_py_path)

        # Create MIB-specific directory (platform-agnostic)
        mib_dir = Path(self.output_dir) / mib_name
        mib_dir.mkdir(parents=True, exist_ok=True)

        json_path = mib_dir / "schema.json"

        if json_path.exists() and not force_regenerate:
            return str(json_path)

        # Extract MIB information (now includes objects and traps)
        extracted_data = self._extract_mib_info(compiled_py_path, mib_name)
        info = extracted_data.get("objects", {})
        traps = extracted_data.get("traps", {})

        self._ensure_table_rows(info, compiled_py_path, mib_name)

        # Write to JSON file (include both objects and traps)
        output_data = {
            "schema_version": SCHEMA_VERSION,
            "objects": info,
            "traps": traps,
        }
        tmp_path = json_path.with_suffix(".json.tmp")
        with tmp_path.open("w", encoding="utf-8") as f:
            f.write(dumps_with_horizontal_oid_lists(output_data, indent=2))
            f.flush()
            os.fsync(f.fileno())
        tmp_path.replace(json_path)

        logger.info(
            "Schema JSON written to %s with %d trap(s)",
            json_path,
            len(traps),
        )
        return str(json_path)

    def _ensure_table_rows(
        self,
        info: dict[str, Any],
        compiled_py_path: str,
        mib_name: str,
    ) -> None:
        """Ensure table metadata contains at least one default row."""
        for table_name, symbol_info in info.items():
            if not isinstance(symbol_info, dict):
                continue

            symbol_type = symbol_info.get("type")
            if symbol_type in {"MibTable", "MibTableRow"} and "type" not in symbol_info:
                symbol_info["type"] = "NoneType"

            if symbol_type != "MibTable":
                continue

            if "rows" not in symbol_info or not isinstance(symbol_info["rows"], list):
                symbol_info["rows"] = []
            if symbol_info["rows"]:
                continue

            self._add_default_table_row(
                info=info,
                table_name=table_name,
                symbol_info=symbol_info,
                compiled_py_path=compiled_py_path,
                mib_name=mib_name,
            )

    def _add_default_table_row(
        self,
        info: dict[str, Any],
        table_name: str,
        symbol_info: dict[str, Any],
        compiled_py_path: str,
        mib_name: str,
    ) -> None:
        """Create and append a default row for a table when no rows are present."""
        entry_info, entry_name = self._find_table_entry(info, symbol_info)
        self._ensure_entry_indexes(entry_info, entry_name, compiled_py_path, mib_name)

        entry_oid = tuple(entry_info.get("oid", []))
        columns = self._find_table_columns(info, entry_oid, table_name, entry_name)
        default_row = self._build_default_row(columns, info, entry_info)
        if default_row:
            rows = cast("list[dict[str, Any]]", symbol_info["rows"])
            rows.append(default_row)

    def _find_table_entry(
        self,
        info: dict[str, Any],
        symbol_info: dict[str, Any],
    ) -> tuple[dict[str, Any], str | None]:
        """Find the MibTableRow entry for a table by matching OID suffix."""
        expected_entry_oid = [*list(symbol_info["oid"]), 1]
        for other_name, other_data in info.items():
            if (
                isinstance(other_data, dict)
                and other_data.get("type") == "MibTableRow"
                and list(other_data.get("oid", [])) == expected_entry_oid
            ):
                return other_data, other_name
        return {}, None

    def _ensure_entry_indexes(
        self,
        entry_info: dict[str, Any],
        entry_name: str | None,
        compiled_py_path: str,
        mib_name: str,
    ) -> None:
        """Best-effort index extraction from compiled MIB metadata."""
        if not entry_info or "indexes" in entry_info or not entry_name:
            return

        try:
            mib_builder = builder.MibBuilder()
            try:
                mib_builder.add_mib_sources(
                    builder.DirMibSource(str(Path(compiled_py_path).parent))
                )
            except MIB_OPERATION_ERRORS:
                with contextlib.suppress(*MIB_OPERATION_ERRORS):
                    mib_builder.add_mib_sources()

            mib_builder.load_modules(mib_name)
            mib_symbols = mib_builder.mibSymbols[mib_name]
            entry_obj = mib_symbols.get(entry_name)
            if isinstance(entry_obj, HasIndexNames):
                entry_info["indexes"] = [idx[2] for idx in entry_obj.getIndexNames()]
        except MIB_OPERATION_ERRORS as err:
            logger.warning("Could not extract index columns for %s: %s", entry_name, err)

    def _find_table_columns(
        self,
        info: dict[str, Any],
        entry_oid: tuple[Any, ...],
        table_name: str,
        entry_name: str | None,
    ) -> list[str]:
        """Return column names that are direct children of the entry OID."""
        columns: list[str] = []
        for col_name, col_info in info.items():
            if not isinstance(col_info, dict):
                continue
            if col_name in [table_name, entry_name]:
                continue
            col_oid = tuple(col_info.get("oid", []))
            if len(col_oid) == len(entry_oid) + 1 and col_oid[: len(entry_oid)] == entry_oid:
                columns.append(col_name)
        return columns

    def _build_default_row(
        self,
        columns: list[str],
        info: dict[str, Any],
        entry_info: dict[str, Any],
    ) -> dict[str, Any]:
        """Build default row values for table columns."""
        default_row: dict[str, Any] = {}
        if not self._type_registry:
            self._type_registry = self._load_type_registry()

        index_names = entry_info.get("indexes", [])
        if not index_names:
            index_names = ["__index__"]
            entry_info["indexes"] = index_names
        if "__index__" in index_names:
            default_row["__index__"] = "1"

        for col in columns:
            col_info = cast("dict[str, Any]", info[col])
            col_type = col_info.get("type", "")
            type_info = self._type_registry.get(col_type, {})
            type_info = self._normalize_type_info_for_symbol(type_info, col_type)
            if "enums" in col_info:
                type_info = {**type_info, "enums": col_info["enums"]}

            if col in index_names:
                default_value = self._get_default_index_value(col_type, type_info)
                if isinstance(default_value, int) and default_value < 1:
                    constraints = type_info.get("constraints", [])
                    has_nonzero_constraint = any(
                        (
                            c.get("min", 0) > 0
                            if isinstance(c, dict) and c.get("type") == "ValueRangeConstraint"
                            else False
                        )
                        for c in constraints
                    )
                    if has_nonzero_constraint or col_type == "InterfaceIndex":
                        default_value = 1
                default_row[col] = default_value
            else:
                default_row[col] = self._get_default_value_from_type_info(type_info, col)

        return default_row

    def _parse_mib_name_from_py(self, compiled_py_path: str) -> str:
        """Parse the MIB name from the compiled Python file (looks for mibBuilder.exportSymbols)."""
        with Path(compiled_py_path).open(encoding="utf-8") as f:
            for line in f:
                if "mibBuilder.exportSymbols" in line:
                    m = re.search(
                        r'mibBuilder\.exportSymbols\(["\"]([A-Za-z0-9\-_.]+)["\"]',
                        line,
                    )
                    if m:
                        return m.group(1)
        # Fallback: use filename without extension
        return Path(compiled_py_path).stem

    def _extract_mib_info(
        self,
        mib_py_path: str,
        mib_name: str,
    ) -> dict[str, Any]:
        """Extract MIB symbol information from a compiled MIB Python file.

        Args:
            mib_py_path: Path to the compiled MIB .py file
            mib_name: Name of the MIB module

        Returns:
            Dictionary mapping symbol names to their metadata

        """
        mib_builder = builder.MibBuilder()
        # Protect against minimal / mocked `builder` objects that lack DirMibSource
        try:
            mib_builder.add_mib_sources(
                builder.DirMibSource(str(Path(mib_py_path).parent))
            )
        except MIB_OPERATION_ERRORS:
            with contextlib.suppress(*MIB_OPERATION_ERRORS):
                mib_builder.add_mib_sources()
        mib_builder.load_modules(mib_name)
        mib_symbols = mib_builder.mibSymbols[mib_name]

        if not isinstance(mib_symbols, dict):
            mib_type = type(mib_symbols)
            mib_repr = repr(mib_symbols)[:500]
            logger.error(
                "mib_symbols for %s is not a dict (type=%s). Value: %s",
                mib_name,
                mib_type,
                mib_repr,
            )
            # Place a breakpoint on the next line to inspect the value of mib_symbols
            msg = f"mib_symbols for {mib_name} is not a dict; cannot extract symbols."
            raise TypeError(msg)

        result = self._build_object_entries(mib_symbols)

        # Detect tables that inherit their index from another table (AUGMENTS pattern)
        # This needs to be done after all symbols are collected
        table_entries = {
            name: obj for name, obj in mib_symbols.items() if isinstance(obj, HasGetIndexNames)
        }
        self._detect_inherited_indexes(result, table_entries, mib_name)

        # Extract trap/notification definitions
        traps = self._extract_traps(mib_symbols, mib_name)
        if traps:
            logger.info(
                "Found %d trap(s) in %s: %s",
                len(traps),
                mib_name,
                list(traps.keys()),
            )

        logger.debug("Extracted MIB info for %s: %s", mib_name, list(result.keys()))
        return {"objects": result, "traps": traps}

    def _build_object_entries(self, mib_symbols: dict[str, Any]) -> dict[str, Any]:
        """Convert raw MIB symbols to schema object entries."""
        if not getattr(self, "_type_registry", None):
            self._type_registry = self._load_type_registry()

        result: dict[str, Any] = {}
        for symbol_name, symbol_obj in mib_symbols.items():
            symbol_name_str = str(symbol_name)
            snapshot = extract_symbol_snapshot(symbol_obj)
            if snapshot is None or snapshot.class_name == "MibScalarInstance":
                continue

            entry = self._build_symbol_entry(snapshot, symbol_name_str)
            result[symbol_name_str] = entry

        return result

    def _build_symbol_entry(self, snapshot: SymbolSnapshot, symbol_name: str) -> dict[str, Any]:
        """Build a single schema entry from a symbol snapshot."""
        symbol_type = snapshot.class_name
        syntax_obj = snapshot.syntax_obj
        is_structural = symbol_type in ("MibTable", "MibTableRow", "MibTableColumn")

        if syntax_obj is not None and syntax_obj.__class__.__name__ != "NoneType":
            type_name = syntax_obj.__class__.__name__
        else:
            type_name = symbol_type

        type_info = self._resolve_type_info(type_name, syntax_obj, symbol_name)
        entry: dict[str, Any] = {
            "oid": snapshot.oid,
            "type": type_name,
            "access": snapshot.access,
        }

        if not is_structural:
            normalized = self._normalize_type_info_for_symbol(type_info or {}, type_name)
            entry["initial"] = self._get_default_value_from_type_info(normalized or {}, symbol_name)
            entry["dynamic_function"] = self._get_dynamic_function(symbol_name)

        if type_info.get("enums"):
            entry["enums"] = type_info["enums"]
        return entry

    def _resolve_type_info(
        self,
        type_name: str,
        syntax_obj: object | None,
        symbol_name: str,
    ) -> dict[str, Any]:
        """Resolve and enrich type info from registry and concrete symbol metadata."""
        type_info = cast("dict[str, Any]", self._type_registry.get(type_name, {}))

        if not type_info and type_name:
            base_type_map: dict[str, str] = {
                "INTEGER": "Integer32",
                "OCTET STRING": "OctetString",
                "OBJECT IDENTIFIER": "ObjectIdentifier",
            }
            mapped_type = base_type_map.get(type_name, type_name) or type_name
            type_info = cast("dict[str, Any]", self._type_registry.get(mapped_type, {}))
            if not type_info:
                type_info = {"base_type": mapped_type}

        if syntax_obj is None or syntax_obj.__class__.__name__ == "NoneType":
            return type_info

        extracted_type_info = self._extract_type_info(syntax_obj, type_name)
        if symbol_name in ("ifAdminStatus", "ifOperStatus"):
            logger.warning(
                "DEBUG %s: extracted enums = %s",
                symbol_name,
                extracted_type_info.get("enums"),
            )

        if extracted_type_info.get("enums"):
            type_info = dict(type_info)
            type_info["enums"] = extracted_type_info["enums"]
        if extracted_type_info.get("constraints"):
            type_info = dict(type_info)
            type_info["constraints"] = extracted_type_info["constraints"]
        return type_info

    def _extract_traps(
        self,
        mib_symbols: dict[str, Any],
        mib_name: str,
    ) -> dict[str, Any]:
        """Extract NOTIFICATION-TYPE definitions from MIB symbols.

        Args:
            mib_symbols: Dictionary of MIB symbols from the compiled MIB
            mib_name: Name of the MIB module

        Returns:
            Dictionary mapping trap names to their metadata (OID, objects, description)

        """
        traps: dict[str, Any] = {}

        for symbol_name, symbol_obj in mib_symbols.items():
            symbol_name_str = str(symbol_name)

            # Check if this is a NotificationType
            if symbol_obj.__class__.__name__ == "NotificationType":
                try:
                    # Get the OID
                    oid = symbol_obj.getName()

                    # Get the OBJECTS list (varbinds that will be sent with the trap)
                    objects = []
                    if isinstance(symbol_obj, HasObjects):
                        obj_refs = symbol_obj.getObjects()
                        pair_len = 2
                        if obj_refs:
                            for obj_ref in obj_refs:
                                # obj_ref holds (mib, name) pairs.
                                if isinstance(obj_ref, tuple) and len(obj_ref) >= pair_len:
                                    obj_mib = str(obj_ref[0])
                                    obj_name = str(obj_ref[1])
                                    objects.append({"mib": obj_mib, "name": obj_name})
                                elif isinstance(obj_ref, Iterable):
                                    # Handle nested tuples
                                    for sub_ref in obj_ref:
                                        if isinstance(sub_ref, tuple) and len(sub_ref) >= pair_len:
                                            obj_mib = str(sub_ref[0])
                                            obj_name = str(sub_ref[1])
                                            objects.append({"mib": obj_mib, "name": obj_name})

                    # Get the description if available
                    description = ""
                    if isinstance(symbol_obj, HasDescription):
                        description = symbol_obj.getDescription() or ""

                    # Get the status
                    status = "current"
                    if isinstance(symbol_obj, HasStatus):
                        status = symbol_obj.getStatus() or "current"

                    traps[symbol_name_str] = {
                        "oid": oid,
                        "objects": objects,
                        "description": description,
                        "status": status,
                        "mib": mib_name,
                    }
                    logger.debug(
                        "Extracted trap %s with OID %s and %d objects",
                        symbol_name_str,
                        oid,
                        len(objects),
                    )
                except (AttributeError, LookupError, OSError, TypeError, ValueError) as e:
                    logger.warning("Failed to extract trap info for %s: %s", symbol_name_str, e)

        return traps

    def _load_type_registry(self) -> dict[str, Any]:
        """Load the canonical type registry from the exported JSON file."""
        registry_path = TYPE_REGISTRY_FILE
        if not registry_path.exists():
            msg = (
                f"Type registry JSON not found at {registry_path}. "
                "Run the type recorder/export step first."
            )
            raise FileNotFoundError(msg)
        with registry_path.open("r", encoding="utf-8") as f:
            return cast("dict[str, Any]", json.load(f))

    def _detect_inherited_indexes(
        self,
        result: dict[str, Any],
        table_entries: dict[str, HasGetIndexNames],
        _mib_name: str,
    ) -> None:
        """Detect tables that inherit their index from another table (AUGMENTS pattern).

        This is common for tables like ifXTable which AUGMENTS ifEntry from ifTable,
        inheriting ifIndex as its index without having the column in its own structure.

        Updates the result dict in-place, adding 'index_from' for entries with inherited indexes.
        """
        for entry_name, entry_obj in table_entries.items():
            try:
                index_names = entry_obj.getIndexNames()
                if not index_names:
                    continue

                # Get the table's OID to find its columns
                entry_oid = tuple(entry_obj.getName())

                # Find columns that belong to this table entry
                table_columns = set()
                for sym_name, sym_info in result.items():
                    sym_oid = tuple(sym_info["oid"])
                    # Columns are direct children of the entry (one OID component deeper)
                    if (
                        len(sym_oid) == len(entry_oid) + 1
                        and sym_oid[: len(entry_oid)] == entry_oid
                    ):
                        table_columns.add(sym_name)

                # Check if index columns are in the table's columns
                # If an index column is NOT in table_columns, it's inherited from another table
                inherited_indexes = []
                for idx_info in index_names:
                    _, idx_mib, idx_col = idx_info
                    if idx_col not in table_columns:
                        inherited_indexes.append({"mib": idx_mib, "column": idx_col})

                # Only mark as inherited if there are actually inherited index columns
                if inherited_indexes and entry_name in result:
                    result[entry_name]["index_from"] = inherited_indexes
            except MIB_OPERATION_ERRORS:
                # Skip if we can't detect - not all objects have getIndexNames
                logger.debug("Skipping inherited-index detection for %s", entry_name)

    def _extract_type_info(self, syntax_obj: object, syntax_name: str) -> dict[str, Any]:
        """Extract detailed type information from a syntax object.

        Returns:
            Dictionary with 'base_type', 'enums' (if applicable), 'constraints', etc.

        """
        # Determine base type by checking the class hierarchy (MRO)
        # For TextualConventions, we want the actual base SNMP type, not the TC name
        base_type = syntax_name

        # Get the class hierarchy
        mro = type(syntax_obj).__mro__

        # Look for the first base SNMP type in the hierarchy by checking class names
        # We check by name because the classes might be from different imports
        base_type_names = [
            "ObjectIdentifier",
            "OctetString",
            "Integer32",
            "Integer",
            "IpAddress",
            "Counter32",
            "Counter64",
            "Gauge32",
            "Unsigned32",
            "TimeTicks",
        ]
        for cls in mro:
            cls_name = cls.__name__
            if cls_name in base_type_names:
                base_type = cls_name
                break

        type_info: dict[str, Any] = {
            "base_type": base_type,
            "enums": None,
            "constraints": None,
        }

        # Extract named values (enumerations)
        named_values = syntax_obj.namedValues if isinstance(syntax_obj, HasNamedValues) else None
        if named_values:
            enums = {}
            for name in named_values:
                value = named_values[name]
                enums[name] = value
            if enums:
                type_info["enums"] = enums

        # Extract constraints
        subtype_spec = syntax_obj.subtypeSpec if isinstance(syntax_obj, HasSubtypeSpec) else None
        if subtype_spec:
            constraints = []
            try:
                # Try to get values attribute (for ConstraintsUnion)
                values = subtype_spec.values if isinstance(subtype_spec, HasValues) else None
                if values:
                    for constraint in values:
                        constraint_info = str(constraint)
                        constraints.append(constraint_info)
                else:
                    # For other constraint types, just convert to string
                    constraints.append(str(subtype_spec))
            except (AttributeError, LookupError, OSError, TypeError, ValueError):
                # If we can't extract constraints, just skip them
                pass
            if constraints:
                type_info["constraints"] = constraints

        return type_info

    def _get_default_index_value(
        self,
        col_type: str,
        type_info: dict[str, Any],
    ) -> object:
        """Get an appropriate default value for an index column based on its type.

        For complex types like IpAddress, returns a representative value.
        For integer types, returns 1.
        """
        # Start with plugin-provided defaults when available, but tolerate missing plugins
        # for index generation so type-based fallbacks still work deterministically.
        try:
            default_value: object = self._get_default_value_from_type_info(type_info, "index")
        except RuntimeError:
            default_value = 1

        if col_type == "IpAddress":
            default_value = "192.168.1.1"
        elif col_type == "InterfaceIndexOrZero":
            default_value = 0
        elif col_type == "InterfaceIndex":
            default_value = 1
        elif col_type in ("Unsigned32", "Integer32", "Integer", "Gauge32"):
            default_value = 1
            if type_info:
                base = str(type_info.get("base_type", ""))
                if "port" in base.lower():
                    default_value = 8080
        elif col_type in ("OctetString", "DisplayString", "PhysAddress"):
            default_value = "default"

        return default_value

    def _get_default_value_from_type_info(
        self,
        type_info: dict[str, Any],
        symbol_name: str,
    ) -> object:
        """Get a sensible default value based on type info and symbol name.

        This method uses the plugin system to determine default values.
        Plugins are called in registration order until one returns a non-None value.

        Raises:
            RuntimeError: If no plugin can provide a default value for the type.

        """
        # Try to get value from plugins
        value = get_default_value(type_info, symbol_name)

        if value is not None:
            return value

        # If no plugin handled it, raise an error - this is a configuration problem
        base_type = type_info.get("base_type", "unknown")
        msg = (
            f"No plugin provided default value for symbol '{symbol_name}' "
            f"(base_type: {base_type}). Please add a plugin to handle this type "
            "in the plugins/ directory or ensure the type is properly registered."
        )
        raise RuntimeError(msg)

    def _normalize_type_info_for_symbol(
        self,
        type_info: dict[str, Any],
        type_name: str,
    ) -> dict[str, Any]:
        """Normalize type metadata when the symbol type should override base_type."""
        if type_name == "IpAddress" and type_info.get("base_type") != "IpAddress":
            normalized = dict(type_info) if type_info else {}
            normalized["base_type"] = "IpAddress"
            return normalized
        return type_info

    def _get_default_value(self, syntax: str, symbol_name: str) -> object:
        """Legacy method - kept for compatibility."""
        symbol_defaults: dict[str, object] = {
            "sysDescr": "Simple Python SNMP Agent - Demo System",
            "sysObjectID": "1.3.6.1.4.1.99999",
            "sysContact": "Admin <admin@example.com>",
            "sysName": "my-pysnmp-agent",
            "sysLocation": "Development Lab",
            "sysUpTime": None,
        }
        if symbol_name in symbol_defaults:
            return symbol_defaults[symbol_name]

        type_defaults: dict[str, object] = {
            "DisplayString": "unset",
            "OctetString": "unset",
            "ObjectIdentifier": "0.0",
            "Integer32": 0,
            "Integer": 0,
            "Gauge32": 0,
            "Unsigned32": 0,
            "Counter32": 0,
            "Counter64": 0,
            "IpAddress": "0.0.0.0",  # noqa: S104
            "TimeTicks": 0,
        }
        return type_defaults.get(syntax)

    def _get_dynamic_function(self, symbol_name: str) -> object:
        """Determine if this symbol should use a dynamic function."""
        if symbol_name == "sysUpTime":
            return "uptime"
        return None
