ADAPTER_EXCEPTIONS: tuple[type[Exception], ...]

class PysnmpRfc1902Adapter:
    def __init__(self, rfc1902_module: object) -> None: ...
    def get_symbol(self, name: str) -> object | None: ...
    def iter_public_symbols(self) -> list[tuple[str, object]]: ...
    @staticmethod
    def has_attribute(obj: object, attr_name: str) -> bool: ...
