from .interfaces import MutableScalarInstance, MibSymbolMap

ADAPTER_EXCEPTIONS: tuple[type[Exception], ...]

class PysnmpMibSymbolsAdapter:
    def __init__(self, mib_builder: object) -> None: ...
    @property
    def _symbols(self) -> MibSymbolMap: ...
    @staticmethod
    def _oid_from_symbol(symbol_obj: object) -> tuple[int, ...] | None: ...
    def load_symbol_class(self, module: str, symbol: str) -> type[object] | None: ...
    def find_scalar_instance_by_oid(
        self,
        oid: tuple[int, ...],
        scalar_instance_cls: type[object],
    ) -> MutableScalarInstance | None: ...
    def get_all_named_oids(self) -> dict[str, tuple[int, ...]]: ...
    def lookup_symbol_for_oid(self, oid: tuple[int, ...]) -> tuple[str | None, str | None]: ...
    def iter_scalar_instances(
        self,
        scalar_instance_cls: type[object],
    ) -> list[tuple[str, str, MutableScalarInstance]]: ...
    def find_scalar_instance_by_candidate_oids(
        self,
        candidate_oids: list[tuple[int, ...]],
        scalar_instance_cls: type[object],
    ) -> MutableScalarInstance | None: ...
    def get_symbol_access(self, symbol_obj: object) -> str | None: ...
    def find_column_oid_for_entry(
        self,
        column_name: str,
        entry_oid: tuple[int, ...],
    ) -> tuple[int, ...] | None: ...
    def find_template_instance_for_column(
        self,
        column_name: str,
        scalar_instance_cls: type[object],
    ) -> tuple[str, MutableScalarInstance, tuple[int, ...]] | None: ...
    def upsert_symbol(self, module_name: str, symbol_name: str, symbol_obj: object) -> bool: ...
